# Generated by Django 6.1.1 on 2026-09-30 12:11

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('rep', 'Sales Rep'), ('front_desk', 'Front Desk')], default='rep', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_lead_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('receives_auto_assign', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('speciality', models.CharField(blank=True, max_length=120)),
                ('calendar_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='crm.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='E.164', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('consult_booked', 'Consult Booked'), ('consult_done', 'Consult Done'), ('treatment_plan_sent', 'Treatment Plan Sent'), ('negotiating', 'Negotiating'), ('treatment_booked', 'Treatment Booked'), ('converted', 'Converted'), ('lost', 'Lost'), ('not_interested', 'Not Interested'), ('invalid', 'Invalid')], db_index=True, default='new', max_length=30)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call-in'), ('walk_in', 'Walk-in'), ('referral', 'Referral'), ('partner', 'Partner / Facilitator'), ('csv', 'CSV Import'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('treatment_interests', models.JSONField(blank=True, default=list)),
                ('chief_complaint', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('budget_band', models.CharField(blank=True, max_length=50)),
                ('insurance', models.CharField(blank=True, max_length=120)),
                ('preferred_days', models.JSONField(blank=True, default=list)),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('preferred_channel', models.CharField(blank=True, max_length=20)),
                ('is_international', models.BooleanField(default=False)),
                ('travel_from', models.DateField(blank=True, null=True)),
                ('travel_to', models.DateField(blank=True, null=True)),
                ('visa_support_needed', models.BooleanField(default=False)),
                ('companions', models.PositiveSmallIntegerField(default=0)),
                ('facilitator', models.CharField(blank=True, max_length=200)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_valid_until', models.DateField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('gclid', models.CharField(blank=True, max_length=255)),
                ('fbclid', models.CharField(blank=True, max_length=255)),
                ('landing_url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_recording', models.BooleanField(default=False)),
                ('whatsapp_opt_out', models.BooleanField(default=False)),
                ('sms_opt_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.crmuser')),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.branch')),
                ('preferred_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('visit', 'Visit')], max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('wrong_number', 'Wrong Number'), ('callback_requested', 'Callback Requested'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], max_length=30)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.lead')),
            ],
            options={
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consult', 'Consultation'), ('treatment', 'Treatment'), ('follow_up', 'Follow-up')], default='consult', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('gcal_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmuser')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.doctor')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='crm.lead')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('channel', 'value')},
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='crm.lead')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.crmuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'ordering': ['is_done', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('rep', 'Sales Rep'), ('front_desk', 'Front Desk')], default='rep', max_length=20)),
                ('token', models.CharField(default=crm.models._invite_token, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=crm.models._invite_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmuser')),
            ],
        ),
    ]
