# Generated by Django 6.1.1 on 2026-10-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gcal_calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gcal_sync_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(blank=True, db_index=True, help_text='Twilio parent (browser) leg', max_length=64)),
                ('child_sid', models.CharField(blank=True, max_length=64)),
                ('to_number', models.CharField(max_length=20)),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('no-answer', 'No answer'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='initiated', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('recording_sid', models.CharField(blank=True, max_length=64)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('logged', models.BooleanField(default=False, help_text='A ContactLog was created from this call')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.crmuser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactlog',
            name='call_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_logs', to='crm.callsession'),
        ),
    ]
