# Generated by Django 6.1.1 on 2026-10-01 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_calls_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue booked when converted (defaults to the quote). Feeds source ROI.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='MarketingSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call-in'), ('walk_in', 'Walk-in'), ('referral', 'Referral'), ('partner', 'Partner / Facilitator'), ('csv', 'CSV Import'), ('manual', 'Manual')], max_length=20)),
                ('campaign', models.CharField(blank=True, help_text='Match the utm_campaign used on landing pages', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmuser')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
